/* eslint-disable @eslint-community/eslint-comments/disable-enable-pair -- auto generated */

/* eslint-disable @eslint-community/eslint-comments/no-unlimited-disable  -- auto generated */

/* eslint-disable -- auto generated  */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root';
import { Route as SettingsRouteImport } from './app/settings';
import { Route as ProfileRouteImport } from './app/profile';
import { Route as GameRouteImport } from './app/game';
import { Route as IndexRouteImport } from './app/index';

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/game': typeof GameRoute;
  '/profile': typeof ProfileRoute;
  '/settings': typeof SettingsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/game' | '/profile' | '/settings';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/game' | '/profile' | '/settings';
  id: '__root__' | '/' | '/game' | '/profile' | '/settings';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GameRoute: typeof GameRoute;
  ProfileRoute: typeof ProfileRoute;
  SettingsRoute: typeof SettingsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/game': {
      id: '/game';
      path: '/game';
      fullPath: '/game';
      preLoaderRoute: typeof GameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
